### ISSUE TITLE
Parsing Improvements

### ISSUE THREAD

**Issue by ngzaharias** [jsoysouvanh/Kodgen#2]
I've been playing around with your code and I had some suggestions.

1. Option to not create generated files for files that aren't annotated
2. Option to always parse namespaces (whether they are annotated or not)
3. ~~Having the output directory for the generated files be a part of the command arguments~~ Never mind, this isn't a part of the library
4. An override function to add extra information to a generated header / source file (extra includes for example)

**Comment by jsoysouvanh** [comment]
Hi, thank you for using Kodgen and for your feedback!

1. This is partially doable. Code generation modules still have the possibility to generate code for files even if no entity has been parsed in a file. It's up to the implementation of each CodeGenModule registered to the CodeGenUnit. However, I could add a check before generating a file. If the generated code is empty, I could skip the file generation step. Note however that this has a performance impact on the long run. A file is processed only if its generated file was written before its source file or if its generated file doesn't exist yet. Because of this second condition, if we don't generate files for "empty" source files, each of these files will go through the file parser and the code generator each single time the code generator is run. If your project has a lot of those files, you will end up extending by a lot the code generation process.

2. This is completely doable and doesn't sound like a bad idea. I will work on it for the next release.

4. You can already do that by creating a CodeGenModule and overriding the initialGenerateCode method. If you use the Macro framework extension, you will have to override either one of initialGenerateHeaderFileHeaderCode / initialGenerateHeaderFileFooterCode / initialGenerateSourceFileHeaderCode. I'm sorry the Wiki still contains some legacy information, I have to work on it ASAP to avoid confusions. Don't forget to add you custom code gen module to your code gen unit before running the generator.

**Comment by jsoysouvanh** [comment]
@ngzaharias I've released a new version (v2.1.0) that implements your 2nd request. Refer to the release notes for more information. Let me know if this works for you.

**Comment by ngzaharias** [comment]
Ah awesome, for 3 I hadn't immeditately found anything, but what you described is what I imagined would be possible. I look forward to trying 

As for 1, with or without, a project with a large number of files would take a while for the parsing anyway, so that wouldn't really change anything. I guess the best case option would be a grep of some sort that only gathers files that have one of the annotation keywords. But you're right that this wouldn't work if you had modules that generated without a annotation.

Thanks again!

**Comment by jsoysouvanh** [comment]
Great, let me know if you struggle with anything, since the wiki is not up-to-date it I bet it's not easy to find the right information.

A project with a large number of files would take a while for parsing/generating **only the first time**. Any subsequent call to the code generator will check if an up-to-date generated file already exists for each file, and if it is the case won't bother reparsing/regenerating code. If we don't generate a file even for "empty" files, we lose this optimization and the generator will have to process files each time no matter what.

I'll consider this issue as closed for now, don't hesitate to reopen it or create a new one if you ever have trouble with anything else :)

Thank you!
