### ISSUE TITLE
Bad int field type detection while generating macro prop code

### ISSUE THREAD

**Issue by MohammadMDSA** [jsoysouvanh/Kodgen#5]
Hi!
Thank you for the excellent lib!
I have numerous types defined across multiple projects glued together with CMake. All my includes are relative or addressed from a root folder that I already have specified in ```addProjectIncludeDirectory``` in parser settings. However, some of my field types are not detected correctly, and the field info containing its type information returns ```int``` as the type, which is incorrect. Is there any best practice for preventing this?

**Comment by jsoysouvanh** [comment]
Hello MohammadMDSA,

Thank you for the kind word!
Since you are mentionning the `addProjectIncludeDirectory` method, I believe you are initializing everything from code?
If so, have you checked that all calls to `addProjectIncludeDirectory` indeed return true? If not, maybe you have made a mistake in one the the provided paths.
If this is fine, are you sure you have specified the paths to all project include directories that are specified in your CMake?

I have helped several people with this same problem and it always was related to a project include directory mistake.
If this doesn't help, may I have a look at the project and see where the problem might come from?
You can also try to enable the logs and see what the generator has to tell you, but libclang might throw unrelevant warnings as well.

**Comment by MohammadMDSA** [comment]
I fixed the problem and faced many others afterwards. As you mentioned it was include directory problem. Now I'm generating code for each of my CMake projects separately, and passing all the project includes defined in cmake as the ganarator arguments. A handy approach which helped me a lot was enabling parser logs and fixing errors in the files I have problem with. Most of the problems were undetected types. I also had to log the name of the file being parsed after "Start Diagnosis" in parsing logs so I would know the scope of each file in logs.
